name: Automatic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install release dependencies
        run: |
          npm install -g semantic-release@22.0.12
          npm install -g @semantic-release/commit-analyzer@11.1.0
          npm install -g @semantic-release/release-notes-generator@12.1.0
          npm install -g @semantic-release/changelog@6.0.3
          npm install -g @semantic-release/git@10.0.1
          npm install -g @semantic-release/github@10.0.7

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release
